
# tasks file for docker

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: add repo docker
  become: true
  command:
    cmd: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Install python3
  yum:
    name: python3
    state: present

- name: Install docker with Python 3
  pip:
    name: docker
    executable: pip3

- name: Ensure Docker is running
  service:
    name: docker
    state: started
  tags: docker

- name: Create Docker network
  docker_network:
    name: my_network
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3.6

- name: Launch database container
  docker_container:
    name: postgres_db
    image: zni0905/tp-devops-database:latest
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    state: started
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    
- name: Launch application container
  docker_container:
    name: my_spring_boot_app
    image: zni0905/tp-devops-simple-api:latest
    networks:
      - name: my_network
    state: started
  vars:
    ansible_python_interpreter: /usr/bin/python3.6

- name: Launch proxy container
  docker_container:
    name: my_apache_container
    image: zni0905/tp-devops-httpd:latest
    ports:
      - "80:80"
    state: started
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3.6

# tasks file for roles/docker
